/* ============================================================
   La bibliothèque des bonjours et bonnes nuits.
   Une lettre différente chaque jour. Mathieu peut en ajouter
   autant qu'il veut : il suffit d'écrire un texte entre
   guillemets, séparé par une virgule.
   ============================================================ */

window.BONJOURS = [
  "Bonjour toi. Si tu lis ces mots, c'est que le jour s'est levé une fois de plus sur nous deux, et ça, ce n'est jamais un détail. Il y a sept ans, je ne savais pas encore que mes matins auraient ton nom. Aujourd'hui je ne sais plus les imaginer autrement. Je voudrais que tu commences cette journée en sachant une chose toute simple : quelque part, quelqu'un a pensé à toi avant même d'avoir complètement ouvert les yeux. Ce quelqu'un t'aime à un point que les mots, même les longs, même les miens, n'arrivent pas tout à fait à contenir. Alors prends ta journée doucement. Bois ton café. Souris à la fenêtre. Et rappelle-toi que tu es, pour moi, la plus belle raison de me réveiller.",

  "Coucou, ma dadouchérie. Je me demande souvent ce que tu es en train de faire à cette heure précise. Est-ce que tu as les cheveux en bataille ? Est-ce que tu grognes contre ton réveil ? Est-ce que tu as déjà ce petit air concentré que j'aime tant ? Peu importe la réponse, elle me fait sourire. Voilà l'effet que tu me fais, même de loin, même dans mon imagination : tu me rends heureux sans rien faire d'autre qu'exister. Aujourd'hui, je te souhaite une journée à ta hauteur. C'est-à-dire une journée douce, lumineuse, et un peu extraordinaire. Comme toi. Je t'aime, et je te le redirai ce soir, et demain, et tous les jours jusqu'à ce que tu me croies enfin complètement.",

  "Bonjour, mon amour. Ce matin, j'ai envie de te parler du temps. On dit qu'il passe vite, et c'est vrai — sept ans ont filé comme un week-end. Mais avec toi, le temps fait quelque chose de bizarre : il passe vite et il reste, en même temps. Chaque souvenir est intact. Lyon est intact. Notre nuit de juillet est intacte. Nos voyages sont intacts. C'est comme si t'aimer m'avait appris à garder les choses. Alors ce matin, je ne te souhaite pas seulement une bonne journée. Je te souhaite une journée qu'on aura envie de garder, une de plus dans notre collection. Va la vivre. Je serai là au bout, à t'attendre, comme toujours.",

  "Réveille-toi doucement, toi. Il n'y a rien à courir après ce matin, rien à réussir avant que je te dise que tu comptes. Tu comptes. Voilà, c'est fait, tu peux commencer ta journée le cœur un peu plus léger. Je sais que tu ne t'exprimes pas toujours facilement, tu me l'as dit toi-même, et je veux que tu saches que ça ne change rien pour moi : je t'entends même dans tes silences. Je te lis même quand tu ne dis rien. Sept ans que je t'apprends par cœur, et je n'ai toujours pas fini, et c'est tant mieux, parce que je compte bien continuer très, très longtemps. Bonne journée, ma dadouchérie.",

  "Bonjour toi. Tu sais ce qui est fou ? On s'est rencontrés sur une application où tout disparaît en dix secondes. Et de tout ce qui aurait dû s'effacer, c'est nous qui sommes restés. Je repense à ça certains matins et je me dis qu'on a battu les probabilités, toi et moi. Deux personnalités aux antipodes, une distance, un début improbable — et pourtant nous voilà. Alors quand aujourd'hui te semblera compliqué, souviens-toi de ça : on est la preuve vivante que les choses improbables arrivent. Nous, on est arrivés. Et je compte bien qu'on continue d'arriver, chaque jour, l'un vers l'autre. Passe une belle journée, je pense à toi déjà trop.",

  "Ma dadouchérie, bonjour. Ce matin, je veux juste te remercier. Pas pour quelque chose de précis — pour tout. Pour ta présence dans ma vie, pour ta patience quand je t'aime à ma façon maladroite, avec des sites web et des mots trop longs. Pour ces sept années où tu m'as supporté, encouragé, accompagné dans les moments joyeux comme dans les difficiles. Tu m'as écrit un jour que je mettais toute mon énergie pour toi ; sache que c'est l'inverse aussi, que tu es mon énergie, ma raison de me lever plus tôt, de faire mieux, de devenir quelqu'un dont tu peux être fière. Va conquérir cette journée. Moi, je t'ai déjà conquise il y a longtemps, et je ne m'en remets pas.",

  "Bonjour, toi qui dors sûrement encore un peu. Je t'imagine, et rien que ça, ma matinée est meilleure. Je voulais te dire quelque chose que je ne dis pas assez : tu es belle. Pas seulement le matin, pas seulement quand tu fais des efforts. Belle tout le temps, belle dans le désordre, belle quand tu ris tellement fort que tu te caches derrière ta main. Belle même quand tu as raison alors que j'étais sûr d'avoir raison — ce qui, statistiquement, arrive bien trop souvent. Aujourd'hui, promets-moi de te regarder au moins une fois avec mes yeux à moi. Tu verrais ce que je vois : la plus belle chose qui me soit arrivée. Bonne journée, mon amour.",

  "Coucou mon cœur. Il paraît qu'on ne devrait pas commencer une journée en pensant à quelqu'un d'autre que soi. J'ai décidé d'ignorer ce conseil il y a sept ans. Chaque matin commence par toi, et je n'ai aucune envie que ça change. Aujourd'hui, où que tu ailles, quoi que tu fasses, emporte-moi un peu avec toi. Pas pour te surveiller, pas pour t'encombrer — juste pour que tu n'aies jamais l'impression d'être seule. Parce que tu ne l'es pas. Tu ne l'as pas été depuis le 1er janvier 2020, et tu ne le seras plus jamais tant que mon cœur voudra bien battre. Et crois-moi, il est très motivé. Passe une douce journée. Je t'aime.",

  "Bonjour, ma dadouchérie. Ce matin, laisse-moi te faire une confidence : il m'arrive de me réveiller avant toi, dans ma tête, et de te regarder dormir en imagination. C'est peut-être un peu fou, mais c'est comme ça que je t'aime — un peu trop, tout le temps, sans raison valable et avec toutes les raisons du monde. Aujourd'hui je te souhaite une journée où tu te sentiras exactement à ta place. Et si le monde oublie de te le rappeler, souviens-toi que moi je le sais : ta place, c'est partout où tu décides d'être, et de préférence pas trop loin de moi. Va, ma belle. Brille. Je regarde d'ici, et je suis fier.",

  "Bonjour toi. Je sais que tu aimes les longs messages, ceux qu'on lit deux fois, ceux qu'on garde. Alors en voilà un, rien que pour ce matin. Je voulais te dire que t'aimer, ce n'est pas une décision que j'ai prise une fois pour toutes. C'est une décision que je reprends chaque jour, chaque matin, en pleine conscience. Et chaque matin, la réponse est la même : oui, encore toi, toujours toi. Pas par habitude — l'habitude, c'est tiède, et nous on n'est pas tièdes. Par évidence. Par choix. Par envie. Alors bonne journée, mon évidence. Fais-en quelque chose de beau, et raconte-moi tout ce soir, même dans le désordre. Surtout dans le désordre. J'adore reconstituer tes histoires comme des puzzles.",

  "Ma dadouchérie, le jour se lève et j'ai déjà envie de te parler. C'est un peu ridicule après sept ans, et pourtant c'est intact. Tu es la seule personne à qui j'ai encore mille choses à dire alors qu'on s'est déjà tout dit. La seule dont le silence ne me pèse jamais et dont les mots ne me lassent jamais. Aujourd'hui, prends soin de toi comme je prendrais soin de toi si j'étais là : mange quelque chose de bon, respire quand ça s'accélère, et souris à un inconnu, ça leur fait toujours de l'effet, ton sourire, j'en sais quelque chose. Passe la plus belle des journées. Moi je compte les heures jusqu'à ce qu'on se retrouve.",

  "Bonjour, mon amour. Ce matin, je pense à toutes les villes qu'on a vues ensemble, et à toutes celles qu'on verra. Monaco, Malte, Barcelone derrière nous. Et devant nous, un monde entier qui n'attend que nous : le Japon et ses cerisiers, la Polynésie et ses lagons, tout ce qu'on s'est promis. Chaque matin nous rapproche un peu de ces jours-là. Alors même si aujourd'hui ressemble à un matin ordinaire, sache qu'il fait partie du chemin vers tout ce qu'on va vivre. On construit ça brique par brique, jour par jour, toi et moi. Va vivre ce lundi, ce mardi, ce jour quelconque et précieux. Il compte, parce que tous nos jours comptent. Je t'aime.",

  "Coucou toi. Je me suis réveillé avec une certitude, la même que d'habitude, mais qui ne s'use jamais : j'ai une chance folle. Une chance insensée de t'avoir trouvée dans cet océan de gens, sur cette petite application de rien du tout, il y a sept ans. Il aurait suffi d'un rien pour qu'on se rate. Un message pas envoyé, un moment mal choisi, et voilà, deux vies qui ne se croisent jamais. Mais on ne s'est pas ratés. On s'est trouvés, et on s'est gardés. Ce matin, je veux juste que tu saches à quel point je mesure cette chance. Tu n'es pas un acquis pour moi. Tu es un miracle quotidien. Bonne journée, mon miracle.",

  "Bonjour, ma dadouchérie. Aujourd'hui, je te confie une petite mission, si tu l'acceptes : sois douce avec toi-même. Tu es tellement forte, tellement courageuse, que tu oublies parfois de te ménager. Alors ce matin, considère-toi comme quelqu'un que quelqu'un aime très fort — parce que c'est le cas. Parle-toi comme je te parlerais. Pardonne-toi tes petites erreurs comme je te les pardonne. Et si la journée devient trop lourde, rappelle-toi qu'il existe un endroit, ce site, où tout n'a été fait que pour te dire une seule chose, déclinée de mille façons : tu es aimée. Voilà. Maintenant va, et reviens-moi entière ce soir. Je t'aime plus que les mots, et pourtant j'en utilise beaucoup."
];

window.BONNES_NUITS = [
  "Bonne nuit, ma dadouchérie. La journée s'éteint doucement, et avant que tu fermes les yeux, je voulais être la dernière voix dans ta tête. Pose tout, maintenant. Les soucis d'aujourd'hui n'ont pas leur place dans ton sommeil ; laisse-les à la porte, ils attendront demain, et demain on sera deux pour les affronter. Cette nuit, ne pense qu'à des choses douces. Pense à nous, à un souvenir qui te fait sourire, à la lumière de Malte ou aux soirées de Barcelone. Et endors-toi en sachant qu'à cette heure précise, quelqu'un t'aime de tout son être et veille sur toi, même de loin, même endormi. Fais de beaux rêves. Je t'y rejoindrai peut-être, si tu me laisses une place.",

  "Il est tard, toi. Le monde s'est tu, les lumières s'éteignent une à une, et moi je pense à toi, comme presque toujours à cette heure-ci. Tu te souviens ? C'est en pleine nuit qu'on s'est tout dit, un 15 juillet. On avait battu le soleil ce soir-là : il s'était levé avant qu'on ait fini de parler. Depuis, les nuits ont un goût particulier pour moi. Elles me ramènent toujours à toi. Alors cette nuit, si tu n'arrives pas à dormir tout de suite, ne t'inquiète pas : c'est notre spécialité, à toi et moi, de rester éveillés quand le monde dort. Mais promets-moi de bien te reposer. J'ai besoin de toi en forme demain, pour continuer à t'aimer sans relâche. Bonne nuit, mon amour.",

  "Bonne nuit, mon cœur. Avant de dormir, fais le tri de ta journée : garde le beau, jette le reste. Les pensées qui tournent en rond à cette heure-là mentent presque toujours ; elles sont énormes la nuit et minuscules le matin, ne les crois pas. Crois plutôt ceci : tu as traversé cette journée, et rien que pour ça, tu peux être fière de toi. Moi je le suis. Je suis fier de toi tous les jours, mais je ne te le dis pas assez, alors je le dis maintenant, dans le calme du soir, quand les mots comptent double. Repose-toi, ma dadouchérie. Le sommeil est le seul endroit où je ne peux pas te suivre, alors vas-y sereine, je garde la porte. À demain.",

  "Ferme les yeux, toi. Tu as le droit de te reposer, maintenant. Tu as assez donné pour aujourd'hui. Je voudrais pouvoir prendre toutes tes fatigues, toutes tes petites inquiétudes, et les emporter loin pour que tu dormes le cœur léger. Comme je ne peux pas le faire dans la vraie vie, je le fais ici, avec des mots : donne-moi tes soucis, cette nuit, je m'en occupe. Toi, tu ne fais qu'une chose, dormir profondément et rêver de choses douces. Rêve de nous, de nos projets, de ces villes qu'on n'a pas encore vues et qui nous attendent. Rêve grand. Et sache qu'à ton réveil, je serai encore là, comme chaque matin depuis sept ans. Bonne nuit, mon amour. Dors bien.",

  "Bonne nuit, ma dadouchérie. Ce soir, je repense au chemin parcouru, et ça me bouleverse un peu. Il y a sept ans, tu étais une notification sur un écran. Aujourd'hui, tu es la dernière personne à qui je pense avant de dormir et la première à qui je pense au réveil. Entre les deux, il y a eu Lyon, il y a eu notre nuit de juillet, il y a eu des voyages, des rires, des moments difficiles qu'on a traversés ensemble. Il y a eu toute une vie qui a commencé sans qu'on s'en rende compte. Alors cette nuit, endors-toi fière de nous, de ce qu'on a construit, deux personnes que tout opposait. On a réussi quelque chose de rare, toi et moi. Repose-toi bien. Je veille.",

  "Il est l'heure de dormir, toi qui ne sais jamais te coucher. Je te connais : tu es sûrement encore en train de faire mille choses, ou de scroller, ou de penser trop. Alors laisse-moi t'aider à ralentir. Respire un grand coup. Encore un. Voilà. Maintenant, imagine que je suis là, à côté de toi, et que je te répète tout bas que tout va bien, que demain est un autre jour, que tu es aimée au-delà du raisonnable. Parce que c'est vrai, tout ça. Je t'aime au-delà du raisonnable, moi l'ingénieur qui aime pourtant les choses mesurables. Toi, tu échappes à toutes mes mesures. Bonne nuit, ma dadouchérie. Fais de beaux rêves, et garde-m'en un ou deux.",

  "Bonne nuit, mon amour. La nuit est tombée et avec elle, tout le vacarme du jour. Il ne reste que le silence, et dans ce silence, il y a toi et moi, même séparés. Je voulais te dire, dans le calme du soir, quelque chose de simple et de vrai : merci pour cette journée passée à savoir que tu existes quelque part. C'est fou comme ta seule existence rend mes journées meilleures. Tu n'as rien à faire pour ça — tu es, et ça me suffit. Maintenant, repose-toi. Laisse la nuit prendre soin de toi comme moi je le ferais. Et demain, on recommence, cette belle habitude de s'aimer un jour de plus. Dors bien, ma dadouchérie. Je t'aime jusqu'aux étoiles, celles que j'ai mises sur ta page et les autres.",

  "Bonne nuit, toi. Regarde par la fenêtre, si tu peux : les étoiles sont là, comme elles étaient là cette nuit de juillet où tout a commencé pour de bon. Elles ne s'impatientent jamais, les étoiles. Elles brillent, c'est tout, patiemment, nuit après nuit. J'aimerais t'aimer comme ça : sans bruit, sans exiger, juste en étant là, fidèle, lumineux dans le noir quand tu as besoin de repères. C'est ce que j'essaie de faire, à ma façon maladroite. Alors cette nuit, si tu te sens seule un instant, lève les yeux : ces étoiles-là, je les regarde peut-être en même temps que toi, et on est un peu ensemble, malgré la distance. Dors bien, ma dadouchérie. Je t'aime, silencieusement et complètement.",

  "Ma dadouchérie, il est temps de dormir. Je sais, tu détestes ça, tu aimerais que les journées ne finissent jamais — moi aussi, quand elles sont belles. Mais le sommeil, c'est juste une virgule, pas un point. Demain, la phrase continue, et je serai encore dedans, avec toi. Cette nuit, je te souhaite le repos le plus doux, celui qui répare tout, celui d'où on se réveille en se disant que finalement, la vie est plutôt bien faite. Parce qu'elle l'est, la vie, quand elle t'a mise sur mon chemin. Ferme les yeux, mon amour. Pose ta tête. Lâche prise. Je t'aime, et cet amour-là ne dort jamais, même quand nous, on dort. Bonne nuit.",

  "Bonne nuit, mon cœur. Ce soir, avant que tu t'endormes, je veux que tu saches une dernière chose : quoi qu'il se soit passé aujourd'hui, bon ou mauvais, tu n'es pas seule pour l'affronter. Tu ne l'as pas été depuis longtemps et tu ne le seras plus jamais. On est une équipe, toi et moi. Une drôle d'équipe, deux caractères aux antipodes, mais une équipe qui gagne, comme tu dis. Alors cette nuit, dépose les armes. Tu n'as plus rien à porter, plus rien à prouver. Juste à te reposer, entre mes pensées et le sommeil. Demain on reprend, ensemble, main dans la main comme d'habitude. Dors bien, ma dadouchérie. Je t'aime plus qu'hier et moins que demain.",

  "Il se fait tard, toi. Le jour t'a peut-être bousculée, ou peut-être gâtée, je ne sais pas encore, tu me raconteras. Mais quoi qu'il en soit, il se termine maintenant, et c'est bien. Chaque jour qui se termine est un jour de plus dans notre histoire, un jour de plus qu'on a vécu en s'aimant, un jour qu'on ne pourra jamais nous reprendre. Ça fait des milliers de jours comme ça, maintenant, et j'en veux des milliers d'autres. Alors dors, pour être prête à en vivre un nouveau demain. Dors, pendant que je compte nos jours passés et que je rêve de nos jours à venir. Bonne nuit, ma dadouchérie. Tu es ma dernière pensée, ce soir comme tous les soirs.",

  "Bonne nuit, mon amour. Je voulais te bercer un peu avec des mots, puisque je ne peux pas le faire avec mes bras ce soir. Alors imagine : imagine qu'on est quelque part, tous les deux, loin de tout. Peut-être en Polynésie, dans un de ces bungalows sur l'eau dont on rêve. On entend l'eau, doucement. Il n'y a rien à faire, nulle part où aller. Juste toi, moi, et le temps arrêté. Un jour, ce sera vrai. En attendant, garde cette image pour t'endormir. Emmène-la dans tes rêves. Et rappelle-toi qu'entre le rêve et la réalité, il n'y a que des jours à traverser, et qu'on les traverse ensemble. Dors bien, ma dadouchérie. Je nous y emmène, un jour, c'est promis.",

  "Bonne nuit, ma dadouchérie. Ce soir, pas de grande philosophie, juste l'essentiel : je t'aime. Je t'aime de cette façon calme et immense qui ne fait pas de bruit mais qui ne s'arrête jamais. Je t'aime les jours faciles et les jours en désordre. Je t'aime quand tout va bien et quand tout va de travers. Je t'aime maintenant, pendant que tu lis, et je t'aimerai encore quand tu dormiras, et encore à ton réveil. C'est le genre d'amour qui ne prend pas de pause. Alors dors tranquille, entourée de ça, protégée par ça. Il n'y a pas plus sûr, comme couverture, qu'un amour qui ne s'éteint pas. Fais de beaux rêves, mon cœur. À demain, comme tous les demains depuis sept ans.",

  "Ferme les yeux, ma dadouchérie. Le monde peut attendre jusqu'à demain. Cette nuit, tu ne dois rien à personne, sauf peut-être à toi-même : le droit de te reposer complètement. Je sais que tu portes beaucoup, souvent en silence, sans te plaindre. Alors ce soir, laisse-moi porter à ta place, ne serait-ce qu'en pensée. Confie-moi ta fatigue, tes petites peurs, tout ce qui pèse. Je le garde pour la nuit. Toi, tu dors, profondément, comme quelqu'un qui sait qu'elle est aimée et en sécurité. Parce que tu l'es, l'une et l'autre. Demain matin, tu retrouveras un monde un peu plus léger, et moi, fidèle au poste, prêt à t'aimer une journée de plus. Bonne nuit, mon amour. Dors comme un ange, tu en es un."
];
