/* ============================================================
   La bibliothèque des bonjours et bonnes nuits.
   Écrite dans la voix de Mathieu. Une lettre différente chaque
   jour. Pour en ajouter : un texte entre guillemets, une virgule.
   ============================================================ */

window.BONJOURS = [
  "Bonjour ma Dadoucherie. Pendant que le monde fait semblant de se réveiller, moi je suis déjà là à penser à toi avant même d'avoir pensé à mon petit-déjeuner, ce qui, tu me connais, relève presque du miracle. Toi tu te réveilles avec un café et deux neurones encore en pyjama, et malgré ça tu arrives à être la personne la plus captivante que je connaisse. Franchement c'est injuste, mais je m'y suis fait. J'espère que tu as bien dormi et que ton café est déjà en train de faire sa petite magie noire habituelle. Prends ta matinée tout doucement, parle au reste de l'humanité seulement quand tu en auras envie, et garde une pensée pour ton vampire émotionnel préféré qui pense beaucoup trop à toi dès le réveil. Je t'aime, mon cœur.",

  "Coucou toi. Je vais te faire une confidence : Paris est un peu trop grande sans toi dedans. Mes habitudes cherchent quelque chose, ou plutôt quelqu'un, et ce quelqu'un est actuellement dans le sud avec son café et sa famille, à vivre à son propre rythme, ce rythme imprévisible et sincère que j'aime tellement observer. Tu me manques dans les détails les plus bêtes. Ta façon de parler quand un truc t'intéresse vraiment. Ton côté je-ne-veux-pas-sortir alors qu'on est déjà le couple le plus casanier de France, deux âmes qui préfèrent rester enfermées ensemble plutôt que d'affronter le monde. Passe une belle matinée, profite des tiens, et sache qu'à cette heure-ci, quelque part, quelqu'un pense à toi bien trop fort pour un simple jour de semaine. Je t'aime, ma catastrophe préférée.",

  "Bonjour, mon étoile. Je me suis réveillé en repensant à un de ces moments où on est juste tous les deux, sans rien faire, et où je me dis que c'est ça le vrai luxe. Pas les grandes sorties, pas le monde entier : juste toi, moi, et le temps qui ralentit. On aura été des nobles ratés au fond, toi dans ton château avec ton café interdit par l'Église, moi t'écrivant des lettres absurdes en latin approximatif pour te séduire. Amor vincit omnia, il paraît, et clairement je suis foutu depuis longtemps. Alors ce matin je ne te demande rien, juste de bien commencer ta journée et de te rappeler, entre deux gorgées de café, que tu es aimée d'une façon un peu ridicule mais totalement sincère. Passe une douce matinée, mon cœur.",

  "Bonjour ma Dadoucherie préférée. Ce matin j'ai envie de te dire un truc simple : merci d'être toi. Merci pour ta douceur que tu ne cherches même pas à avoir, pour ton humour que tu sors sans le vouloir, pour cette manière que tu as d'exister pleinement même dans le silence, même quand tu ne réponds pas tout de suite parce que tu es dans ton monde avec tes pensées qui partent dans mille directions. Je pourrais passer des heures juste à te regarder vivre. Aujourd'hui, où que tu ailles, emporte-moi un peu avec toi. Pas pour t'encombrer, juste pour que tu n'aies jamais l'impression d'être seule, parce que tu ne l'es pas, et tu ne le seras plus. Je t'aime, profite bien de ta matinée et de ton café sacré.",

  "Coucou mon cœur. Je t'imagine ce matin, le regard encore un peu fatigué, le café à la main, pas franchement d'humeur à parler à qui que ce soit, et honnêtement rien que cette image me rend heureux. C'est fou l'effet que tu me fais, même de loin, même dans ma tête. Ça fait un moment qu'on ne s'est pas vus et mon cerveau commence sérieusement à buguer sans toi, je crois. Il a pris l'habitude de te garder quelque part en fond sonore, dans toutes mes journées, et franchement ça me plaît énormément. Alors passe une belle matinée, prends soin de toi comme je le ferais si j'étais là, et garde-moi une petite place dans tes pensées éparpillées. Tu me manques, plus que je ne le dis. Je t'aime.",

  "Bonjour toi. Tu sais ce qui me fait sourire ce matin ? L'idée qu'un jour, on se réveillera dans le même appartement. Je te préparerai un vrai petit-déjeuner, avec tout ce qu'il faut, et tu l'ignoreras royalement au profit de ton café noir, et ce jour-là je serai probablement l'homme le plus heureux et le plus vexé de France en même temps. On en a tellement parlé, de cette vie à deux, des villes, des appartements, de nos habitudes qui s'agacent, de tout ce quotidien qui fait un peu peur mais qui me fait surtout envie parce que c'est avec toi. Alors ce matin, en attendant ce jour, sache que je le construis dans ma tête pièce par pièce, et que tu es dans chacune d'elles. Passe une belle journée, mon amour.",

  "Bonjour ma Dadoucherie. Petite pensée du matin, comme un vieux poète abandonné dans un appartement trop silencieux : tu es douce sans essayer de l'être, drôle sans le vouloir, et attachante d'une manière presque dangereuse. Shakespeare aurait rangé sa plume s'il t'avait rencontrée avant Juliette, je te le dis. Je sais qu'on est différents, qu'on ne fait pas les choses de la même façon, qu'on se prend parfois la tête pour des broutilles comme tous les couples. Mais je sais aussi qu'il n'y a jamais eu personne avec qui je me sois senti aussi bien à imaginer l'avenir. Alors passe une belle matinée, profite de ton café et des tiens, et garde en tête que dans le sud comme à Paris, il y a un cœur qui bat un peu trop vite dès qu'il pense à toi. Je t'aime.",

  "Coucou mon étoile. Réveil difficile ? Café pas encore assez fort ? Envie de renvoyer le monde entier se recoucher ? Je comprends, et je t'aime encore plus pour ça. On est pareils, toi et moi, deux vampires émotionnels qui trouvent que le matin arrive toujours un peu trop tôt et que les gens font toujours un peu trop de bruit. Alors ce matin, va à ton rythme. Le monde attendra que ton café ait fait effet, il n'a pas le choix. Moi en attendant je pense à toi, à ta manière unique de traverser tes journées, épuisée socialement mais toujours prête à faire l'effort pour ceux que tu aimes. C'est une des mille choses qui me rendent complètement accro à toi. Passe une belle matinée, ma catastrophe préférée. Je t'aime fort.",

  "Bonjour, mon cœur. Ce matin je repense au concert, à vous tous réunis, à cette sensation étrange et magnifique de vous avoir tous avec moi ce soir-là, et surtout à toi au milieu de tout ça. J'y repense souvent, tu sais. Il y a des soirs comme ça qui restent, qui s'accrochent quelque part et qui reviennent te réchauffer les matins gris. Aujourd'hui je te souhaite une journée douce, entourée de ta famille et de ce sud qui te va si bien. Profite d'eux, ris fort, sois dans ton élément. Et de temps en temps, entre deux gorgées de café, souviens-toi qu'à Paris quelqu'un compte les jours jusqu'à te revoir et invente des mots absurdes en latin pour te dire je t'aime. Mi corazón, ma étoile, ma Dadoucherie. Passe une belle matinée.",

  "Bonjour toi. Aujourd'hui, une seule mission, si tu l'acceptes : sois un peu douce avec toi-même. Tu portes beaucoup, souvent sans le dire, et tu oublies parfois de te ménager. Alors ce matin, considère-toi comme quelqu'un que quelqu'un aime très fort, parce que c'est exactement le cas. Parle-toi comme je te parlerais. Pardonne-toi tes petites erreurs comme je te les pardonne, c'est-à-dire immédiatement et complètement. Et si la journée devient lourde, rappelle-toi qu'il existe cet endroit, ce site, où tout n'a été fait que pour te répéter une seule chose de mille façons différentes : tu es aimée. Va, mon cœur. Bois ton café, respire, et reviens-moi entière ce soir. Je t'aime, même quand tu ne sais pas quoi répondre, surtout quand tu ne sais pas quoi répondre.",

  "Coucou ma Dadoucherie. Il y a un truc bizarre et beau que je voulais te dire ce matin : malgré la distance, malgré les jours, malgré nos rythmes complètement différents, je te sens toujours proche de moi. Comme si mon cerveau avait décidé une fois pour toutes de te garder allumée quelque part, en permanence. Aimer quelqu'un comme toi, ce n'est pas quelque chose de calme et de tranquille, tu sais. C'est beau, un peu bordélique, parfois intense, mais tellement vivant. Et je ne changerais ça pour rien au monde. Alors quand tu te réveilleras, avant même d'avoir envie de parler à qui que ce soit, j'espère que ce message te fera sourire un peu, même discrètement, même juste avec ce petit regard fatigué que j'imagine parfaitement d'ici. Tu me manques. Passe une belle matinée, mon amour.",

  "Bonjour mon cœur. Je crois qu'on est officiellement le couple qui préfère un canapé et un silence à deux plutôt qu'une soirée avec cinquante personnes, et honnêtement, c'est une des raisons pour lesquelles je nous trouve parfaits. On n'a rien à prouver à personne, toi et moi. On est bien dans notre petit monde, avec nos habitudes, nos manies, nos disputes pour des broutilles et nos réconciliations qui vont toujours plus vite qu'on ne l'imagine. Ce matin je te souhaite une journée à ta sauce : ni trop de bruit, ni trop de monde, juste ce qu'il faut de café et de gens que tu aimes. Et ce soir, si tu veux, on refera semblant d'être des vampires antisociaux, chacun de notre côté pour l'instant, mais bientôt sous le même toit. Je t'aime, passe une belle matinée."
];

window.BONNES_NUITS = [
  "Bonne nuit, ma Dadoucherie. La journée s'éteint doucement et avant que tu fermes les yeux, je voulais être la dernière voix dans ta tête. Pose tout maintenant. Les tracas d'aujourd'hui n'ont pas leur place dans ton sommeil, laisse-les à la porte, ils attendront demain, et demain on sera deux pour les affronter. Cette nuit ne pense qu'à des choses douces, à nous, à un souvenir qui te fait sourire. Et endors-toi en sachant qu'à cette heure précise, un vampire émotionnel dans le sud de sa tête pense fort à toi et veille sur toi, même de loin. Fais de beaux rêves, mon cœur. Et si tu me gardes une place dedans, je viendrai.",

  "Il est tard, toi, et je te connais : tu es sûrement encore réveillée à faire mille choses ou à laisser tes pensées partir dans toutes les directions. On est pareils, deux insomniaques du cœur qui trouvent que la nuit est le meilleur moment pour réfléchir. Mais ce soir, laisse-moi t'aider à ralentir. Respire un grand coup. Pose ton téléphone bientôt. Imagine qu'on est déjà dans notre futur appartement, toi avec ton café interdit à cette heure-ci, moi en train de râler gentiment que tu ne dors pas, et endors-toi sur cette image. Un jour ce sera vrai. En attendant, repose-toi, mon étoile. Je t'aime plus que je ne le dis, et je te le redirai demain matin, promis.",

  "Bonne nuit, mon cœur. Fais le tri de ta journée avant de dormir : garde le beau, jette le reste. Les pensées qui tournent en rond à cette heure-là mentent presque toujours, elles sont énormes la nuit et minuscules le matin, ne les crois pas. Crois plutôt ceci : tu as traversé cette journée, et rien que pour ça je suis fier de toi. Je le suis tous les jours mais je ne te le dis pas assez, alors je le dis maintenant, dans le calme du soir, quand les mots comptent double. Repose-toi, ma Dadoucherie. Le sommeil est le seul endroit où je ne peux pas encore te suivre, alors vas-y sereine, je garde la porte de loin. À demain, mon amour.",

  "Ferme les yeux, toi. Tu as le droit de te reposer maintenant, tu as assez donné pour aujourd'hui. Je voudrais pouvoir prendre toutes tes fatigues et toutes tes petites inquiétudes et les emporter loin pour que tu dormes le cœur léger. Comme je ne peux pas le faire pour de vrai ce soir, je le fais avec des mots : donne-moi tes soucis cette nuit, je m'en occupe, toi tu ne fais qu'une chose, dormir profondément. Rêve de nous, de nos projets, de cette vie à deux dont on parle depuis si longtemps, des villes qu'on n'a pas encore vues et qui nous attendent. Rêve grand. Et sache qu'à ton réveil je serai là, comme toujours. Bonne nuit, mon cœur. Dors bien.",

  "Bonne nuit, mon étoile. Ce soir la distance me pèse un peu, je vais être honnête. Paris est trop silencieuse, mon appartement trop vide, et toi tu es dans le sud, loin, entourée des tiens, à vivre ta vie que j'aime tant observer de loin. Mais tu sais quoi ? Même séparés, je te sens proche. Mon cerveau t'a mise en fond sonore et refuse de t'éteindre, et franchement je le laisse faire. Alors cette nuit, où que tu sois, dors bien pour nous deux. Repose-toi, recharge-toi, et rêve un peu de ce jour où on n'aura plus à se dire bonne nuit à distance parce qu'on sera enfin sous le même toit. Ce jour arrive. Je t'aime, ma Dadoucherie. Dors bien.",

  "Il se fait tard, ma catastrophe préférée. Le jour t'a peut-être bousculée ou peut-être gâtée, tu me raconteras. Mais quoi qu'il en soit il se termine maintenant, et c'est très bien. Chaque jour qui s'achève est un jour de plus qu'on aura vécu en s'aimant, un de plus dans notre histoire, un qu'on ne pourra jamais nous reprendre. J'en veux des milliers d'autres comme ça. Alors dors, pour être prête à en vivre un nouveau demain. Dors, pendant que je pense à toi comme un vieux noble amoureux qui aurait traversé des royaumes juste pour te voir lever les yeux au petit matin. Ridicule ? Oui. Sincère ? Encore plus. Bonne nuit, mon cœur. Tu es ma dernière pensée, ce soir comme tous les soirs.",

  "Bonne nuit, mon amour. Pas de grande philosophie ce soir, juste l'essentiel : je t'aime. De cette façon calme et immense qui ne fait pas de bruit mais qui ne s'arrête jamais. Je t'aime les jours faciles et les jours en désordre, quand tout va bien et quand on se prend la tête pour des broutilles. Je t'aime maintenant, pendant que tu lis, et je t'aimerai encore quand tu dormiras, et encore à ton réveil avec ton café et ton air pas commode. C'est le genre d'amour qui ne prend pas de pause, même la nuit. Alors dors tranquille, entourée de ça, protégée par ça. Il n'y a pas de meilleure couverture qu'un amour qui ne s'éteint pas. Fais de beaux rêves, ma Dadoucherie. À demain.",

  "Ferme les yeux, mon cœur. Le monde peut attendre demain. Cette nuit tu ne dois rien à personne, sauf peut-être à toi-même : le droit de te reposer complètement. Je sais que tu portes beaucoup, souvent en silence, sans te plaindre, épuisée mais toujours debout pour les tiens. Alors ce soir laisse-moi porter à ta place, au moins en pensée. Confie-moi ta fatigue, tes petites peurs, tout ce qui pèse, je le garde pour la nuit. Toi tu dors, profondément, comme quelqu'un qui sait qu'elle est aimée et en sécurité, parce que tu l'es, l'une et l'autre. Demain tu retrouveras un monde un peu plus léger, et moi fidèle au poste, prêt à t'aimer une journée de plus. Bonne nuit, ma Dadoucherie.",

  "Bonne nuit, toi. Regarde par la fenêtre si tu peux, les étoiles sont là. Elles ne s'impatientent jamais, elles brillent, c'est tout, patiemment, nuit après nuit. J'aimerais t'aimer comme ça, sans bruit, sans rien exiger, juste en étant là, fidèle, lumineux dans le noir quand tu as besoin de repères. C'est ce que j'essaie de faire, à ma façon maladroite de poète du dimanche. Alors cette nuit, si tu te sens seule un instant, lève les yeux : ces étoiles-là, je les regarde peut-être en même temps que toi depuis Paris, et on est un peu ensemble, malgré les kilomètres. Dors bien, ma Dadoucherie. Je t'aime, silencieusement et complètement.",

  "Ma Dadoucherie, il est l'heure de dormir. Je sais, tu détestes ça, tu aimerais que les bonnes journées ne finissent jamais, moi aussi. Mais le sommeil c'est juste une virgule, pas un point. Demain la phrase continue, et je serai encore dedans, avec toi. Cette nuit je te souhaite le repos le plus doux, celui qui répare tout, celui d'où on se réveille en se disant que finalement la vie est plutôt bien faite. Parce qu'elle l'est, quand elle t'a mise sur mon chemin, même à distance, même compliquée parfois. Ferme les yeux, mon amour, pose ta tête, lâche prise. Je t'aime, et cet amour-là ne dort jamais, même quand nous on dort. Bonne nuit, ma catastrophe préférée.",

  "Bonne nuit, mon étoile. Je voulais te bercer un peu avec des mots puisque je ne peux pas le faire avec mes bras ce soir. Alors imagine : imagine qu'on est loin de tout, tous les deux, quelque part rien qu'à nous, peut-être dans un de ces endroits dont on rêve. Il n'y a rien à faire, nulle part où aller, personne à voir, ce qui pour deux casaniers comme nous ressemble au paradis. Juste toi, moi, et le temps arrêté. Un jour ce sera vrai. En attendant, garde cette image pour t'endormir, emmène-la dans tes rêves. Et rappelle-toi qu'entre le rêve et la réalité, il n'y a que des jours à traverser, et qu'on les traverse ensemble. Dors bien, ma Dadoucherie. Je nous y emmène un jour, c'est promis.",

  "Bonne nuit, mon cœur. Avant que tu t'endormes, une dernière chose : quoi qu'il se soit passé aujourd'hui, bon ou mauvais, tu n'es pas seule pour l'affronter, et tu ne le seras plus. On est une équipe, toi et moi, une drôle d'équipe aux caractères opposés, mais une équipe qui gagne. Alors cette nuit dépose les armes, tu n'as plus rien à porter ni à prouver, juste à te reposer entre mes pensées et le sommeil. Demain on reprend, ensemble, même à distance, en attendant le jour où on partagera vraiment le même lit et les mêmes matins compliqués. Dors bien, ma Dadoucherie. Je t'aime plus qu'hier et bien moins que demain."
];
